/**
 * droneVoiceProcessor — generated by scripts/build-worklet.mjs.
 * DO NOT EDIT THIS FILE DIRECTLY — edit the source under
 * src/engine/voices/ and re-run `npm run prebuild`.
 *
 * This worklet is loaded by Vite via `?url` import and registered
 * into AudioWorkletGlobalScope. AudioWorklet cannot portably import
 * ES modules, so the source is split for maintainability and
 * concatenated here to ship as a single file.
 */

/* sampleRate, AudioWorkletProcessor, registerProcessor are globals in AudioWorkletGlobalScope */
/* global sampleRate, AudioWorkletProcessor, registerProcessor */


// ══ shared.js ══════════════════════════════════════════════════

// Shared DSP helpers for the mdrone voice worklet. This module is
// concatenated into `src/engine/droneVoiceProcessor.js` by
// `scripts/build-worklet.mjs` during the `prebuild` step. AudioWorklet
// does not yet universally support ES module imports, so we stage the
// split via physical file separation + build-time concatenation; the
// runtime worklet stays a single JS file the way Vite's `?url` loader
// expects.
//
// Runtime globals (sampleRate, AudioWorkletProcessor, registerProcessor,
// currentTime) are provided by AudioWorkletGlobalScope; they are used
// here purely for reference and are not redeclared.


// ─── Mulberry32 PRNG — seeded, deterministic, cheap ──────────────────
function makeRng(seed) {
  let state = (seed * 2654435761) | 0;
  return () => {
    state = (state + 1831565813) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ─── Sine wavetable — replaces per-sample Math.sin in hot loops ──
const SINE_TABLE_SIZE = 4096;
const SINE_TABLE = new Float32Array(SINE_TABLE_SIZE + 1); // +1 for lerp guard
for (let i = 0; i <= SINE_TABLE_SIZE; i++) {
  SINE_TABLE[i] = Math.sin((i / SINE_TABLE_SIZE) * Math.PI * 2);
}
const SINE_INC = SINE_TABLE_SIZE / (Math.PI * 2);
function fastSin(phase) {
  const idx = ((phase % 6.283185307179586) + 6.283185307179586) * SINE_INC;
  const i = idx | 0;
  return SINE_TABLE[i % SINE_TABLE_SIZE] + (idx - i) * (SINE_TABLE[(i + 1) % SINE_TABLE_SIZE] - SINE_TABLE[i % SINE_TABLE_SIZE]);
}

// ─── PolyBLEP — bandlimited discontinuity correction ────────────
// Used by the reed "even" (bowed-string) shape to produce a
// sawtooth with natural harmonic content instead of summing sines.
function polyblep(phase01, dt) {
  if (phase01 < dt) {
    const t = phase01 / dt;
    return t + t - t * t - 1;
  }
  if (phase01 > 1 - dt) {
    const t = (phase01 - 1) / dt;
    return t * t + t + t + 1;
  }
  return 0;
}

// ─── 2× polyphase IIR halfband oversampler ──────────────────────
// 4th-order Niemitalo minphase halfband: two parallel branches of
// 2 cascaded 1st-order allpasses each. Stopband ≈ -70 dB, CPU ≈ 8
// multiply-adds per input sample for the full up/down round-trip.
const HB_A0 = 0.07986641281610;
const HB_A1 = 0.54530488711;
const HB_B0 = 0.28393847843;
const HB_B1 = 0.86930964090;

// Denormal flush threshold. JavaScriptCore (Safari/iOS) doesn't flush
// subnormals; V8 (Chrome) effectively does. With ~8 per-sample IIR
// feedback loops per voice × 7 voices, subnormal state accumulates on
// iPhone and produces signal-correlated "frrrr" hash that's inaudible
// on Chrome/Mac. Flushing values this tiny is far below any audible
// threshold (-400 dBFS) so it never affects normal signal.
const HB_DENORMAL = 1e-20;
function flushDenormal(x) {
  return x > HB_DENORMAL || x < -HB_DENORMAL ? x : 0;
}

class Halfband2x {
  constructor() {
    this.ua0x = 0; this.ua0y = 0;
    this.ua1x = 0; this.ua1y = 0;
    this.ub0x = 0; this.ub0y = 0;
    this.ub1x = 0; this.ub1y = 0;
    this.da0x = 0; this.da0y = 0;
    this.da1x = 0; this.da1y = 0;
    this.db0x = 0; this.db0y = 0;
    this.db1x = 0; this.db1y = 0;
  }

  process(x, fn) {
    let a = HB_A0 * x + this.ua0x - HB_A0 * this.ua0y;
    a = flushDenormal(a);
    this.ua0x = x; this.ua0y = a;
    let aOut = HB_A1 * a + this.ua1x - HB_A1 * this.ua1y;
    aOut = flushDenormal(aOut);
    this.ua1x = a; this.ua1y = aOut;
    let b = HB_B0 * x + this.ub0x - HB_B0 * this.ub0y;
    b = flushDenormal(b);
    this.ub0x = x; this.ub0y = b;
    let bOut = HB_B1 * b + this.ub1x - HB_B1 * this.ub1y;
    bOut = flushDenormal(bOut);
    this.ub1x = b; this.ub1y = bOut;

    const na = fn(aOut);
    const nb = fn(bOut);

    let da = HB_A0 * na + this.da0x - HB_A0 * this.da0y;
    da = flushDenormal(da);
    this.da0x = na; this.da0y = da;
    let daOut = HB_A1 * da + this.da1x - HB_A1 * this.da1y;
    daOut = flushDenormal(daOut);
    this.da1x = da; this.da1y = daOut;
    let db = HB_B0 * nb + this.db0x - HB_B0 * this.db0y;
    db = flushDenormal(db);
    this.db0x = nb; this.db0y = db;
    let dbOut = HB_B1 * db + this.db1x - HB_B1 * this.db1y;
    dbOut = flushDenormal(dbOut);
    this.db1x = db; this.db1y = dbOut;
    return 0.5 * (daOut + dbOut);
  }

  reset() {
    this.ua0x = this.ua0y = this.ua1x = this.ua1y = 0;
    this.ub0x = this.ub0y = this.ub1x = this.ub1y = 0;
    this.da0x = this.da0y = this.da1x = this.da1y = 0;
    this.db0x = this.db0y = this.db1x = this.db1y = 0;
  }

  sanitize() {
    const bad = !Number.isFinite(this.ua0y) || !Number.isFinite(this.ua1y)
             || !Number.isFinite(this.ub0y) || !Number.isFinite(this.ub1y)
             || !Number.isFinite(this.da0y) || !Number.isFinite(this.da1y)
             || !Number.isFinite(this.db0y) || !Number.isFinite(this.db1y);
    if (bad) this.reset();
  }
}



// ══ core.js ══════════════════════════════════════════════════

// mdrone voice worklet — core class. Defines DroneVoiceProcessor with
// its constructor, shared helpers (pinkNoise, sanitizeState), and the
// per-block process() dispatcher. Per-voice init/process methods
// (initTanpura/tanpuraProcess, initReed/reedProcess, ...) are
// attached as prototype extensions by separate files under this
// directory and concatenated after core.js by
// scripts/build-worklet.mjs. The `registerProcessor` call lives in
// register.js (concatenated last) so extensions always land before
// the processor is registered with the worklet global scope.


class DroneVoiceProcessor extends AudioWorkletProcessor {
  static get parameterDescriptors() {
    return [
      { name: "freq",  defaultValue: 220, minValue: 20, maxValue: 8000, automationRate: "k-rate" },
      { name: "drift", defaultValue: 0.3, minValue: 0,  maxValue: 1,    automationRate: "k-rate" },
      { name: "amp",   defaultValue: 0,   minValue: 0,  maxValue: 2,    automationRate: "k-rate" },
      // Tanpura re-pluck rate multiplier. 1 = default, 0 = hold
      // (infinite sustain, no repluck). Ignored by non-tanpura.
      { name: "pluckRate", defaultValue: 1, minValue: 0, maxValue: 4, automationRate: "k-rate" },
      // NOISE voice COLOR: 0 = white, 0.3 = pink, 0.6 = brown,
      // 1 = sub-rumble. Ignored by all other voice types.
      { name: "color", defaultValue: 0.3, minValue: 0, maxValue: 1, automationRate: "k-rate" },
    ];
  }

  constructor(options) {
    super();
    const opts = options?.processorOptions || {};
    this.voiceType = opts.voiceType || "tanpura";
    this.reedShape = opts.reedShape || "odd";
    // Tanpura string tuning — see TANPURA_TUNING_RATIOS in tanpura.js.
    // Default "classic" = pre-P3 unison micro-detune so scenes reload
    // identically unless the preset / UI explicitly picks a tuning.
    this.tanpuraTuningOpt = opts.tanpuraTuning || "classic";
    this.fmRatioOpt = opts.fmRatio || 2.0;
    this.fmIndexOpt = opts.fmIndex || 2.4;
    this.fmFeedbackOpt = opts.fmFeedback || 0;
    this.seed = opts.seed || 1;
    this.rng = makeRng(this.seed);

    // Termination flag — main thread posts {type:"stop"} when the
    // voice is retired. process() returns false once set, so the
    // worklet processor is GC-eligible instead of running forever.
    this.stopped = false;
    // ENTRAIN dichotic L/R spread, in cents on the R channel. Stored
    // pre-computed as a ratio multiplier so the per-sample voice
    // loops only pay one extra float multiply. 1 = no effect.
    this.dichoticMulR = 1;
    this.port.onmessage = (e) => {
      const msg = e.data;
      if (!msg) return;
      if (msg.type === "stop") { this.stopped = true; return; }
      if (msg.type === "dichotic") {
        const cents = typeof msg.cents === "number" ? msg.cents : 0;
        this.dichoticMulR = Math.pow(2, cents / 1200);
      }
    };

    // Pink noise filter state (Paul Kellet) — shared by voices that need it
    this.pink = { b0: 0, b1: 0, b2: 0, b3: 0, b4: 0, b5: 0, b6: 0 };

    // Per-voice init
    switch (this.voiceType) {
      case "tanpura": this.initTanpura(); break;
      case "reed":    this.initReed();    break;
      case "metal":   this.initMetal();   break;
      case "air":     this.initAir();     break;
      case "piano":   this.initPiano();   break;
      case "fm":      this.initFm();      break;
      case "amp":     this.initAmp();     break;
      case "noise":   this.initNoise();   break;
      default:        this.initTanpura(); break;
    }
  }

  // ── PINK NOISE (shared helper) ───────────────────────────────────
  pinkNoise() {
    const p = this.pink;
    const white = this.rng() * 2 - 1;
    p.b0 = 0.99886 * p.b0 + white * 0.0555179;
    p.b1 = 0.99332 * p.b1 + white * 0.0750759;
    p.b2 = 0.969  * p.b2 + white * 0.153852;
    p.b3 = 0.8665 * p.b3 + white * 0.3104856;
    p.b4 = 0.55   * p.b4 + white * 0.5329522;
    p.b5 = -0.7616 * p.b5 - white * 0.016898;
    const out = p.b0 + p.b1 + p.b2 + p.b3 + p.b4 + p.b5 + p.b6 + white * 0.5362;
    p.b6 = white * 0.115926;
    return out * 0.11;
  }

  // ── STATE SANITATION ─────────────────────────────────────────────
  // Guards every feedback-rich scalar against NaN / Infinity that
  // would otherwise latch the voice at silence or subsonic DC. Called
  // once per block from process(); O(voiceState) but state is small.
  // Shared helper for per-voice sanitize methods. Counts fires per field
  // and increments _nanFires so the periodic diag emit can post counts
  // back to the main thread.
  _fix(name, v) {
    if (Number.isFinite(v)) return v;
    this._nanFires = (this._nanFires | 0) + 1;
    if (!this._nanFieldCounts) this._nanFieldCounts = Object.create(null);
    this._nanFieldCounts[name] = (this._nanFieldCounts[name] | 0) + 1;
    return 0;
  }

  // Per-voice sanitize methods — only touch the state fields the voice
  // actually uses. Avoids firing on uninitialized cross-voice prototype
  // state at boot (the diagnostic showed the previous unconditional
  // sweep produced ~30 init-noise fires per voice instance with no
  // real audio-processing significance).
  _sanitizeTanpura() {
    this.ksBodyLowL  = this._fix("ksBodyLowL",  this.ksBodyLowL);
    this.ksBodyBandL = this._fix("ksBodyBandL", this.ksBodyBandL);
    this.ksBodyLowR  = this._fix("ksBodyLowR",  this.ksBodyLowR);
    this.ksBodyBandR = this._fix("ksBodyBandR", this.ksBodyBandR);
    this.hsKsL = this._fix("hsKsL", this.hsKsL);
    this.hsKsR = this._fix("hsKsR", this.hsKsR);
    if (this.ksLasts)  for (let i = 0; i < this.ksLasts.length;  i++) this.ksLasts[i]  = this._fix("ksLasts",  this.ksLasts[i]);
    if (this.ksLastsR) for (let i = 0; i < this.ksLastsR.length; i++) this.ksLastsR[i] = this._fix("ksLastsR", this.ksLastsR[i]);
    if (this.jawHbL) for (const hb of this.jawHbL) hb.sanitize();
    if (this.jawHbR) for (const hb of this.jawHbR) hb.sanitize();
  }

  _sanitizeReed() {
    if (this.reedFormN) {
      for (let i = 0; i < this.reedFormN; i++) {
        this.reedFormLowL[i]  = this._fix("reedFormLowL",  this.reedFormLowL[i]);
        this.reedFormBandL[i] = this._fix("reedFormBandL", this.reedFormBandL[i]);
        this.reedFormLowR[i]  = this._fix("reedFormLowR",  this.reedFormLowR[i]);
        this.reedFormBandR[i] = this._fix("reedFormBandR", this.reedFormBandR[i]);
      }
    }
    this.hsReedL = this._fix("hsReedL", this.hsReedL);
    this.hsReedR = this._fix("hsReedR", this.hsReedR);
  }

  _sanitizeAir() {
    if (this.airStates) {
      for (let i = 0; i < this.airStates.length; i++) {
        const s = this.airStates[i];
        s[0] = this._fix("airState0", s[0]);
        s[1] = this._fix("airState1", s[1]);
        s[2] = this._fix("airState2", s[2]);
        s[3] = this._fix("airState3", s[3]);
      }
    }
    // hsL/hsR were vestigial — no voice initializes or writes them. The
    // 1.20.10 diagnostic surfaced this as `voice=air fires=2 {hsL: 1, hsR: 1}`
    // after the per-voice scoping in 1.20.11. Removed.
  }

  _sanitizePiano() {
    this.pianoBodyLowL  = this._fix("pianoBodyLowL",  this.pianoBodyLowL);
    this.pianoBodyBandL = this._fix("pianoBodyBandL", this.pianoBodyBandL);
    this.pianoBodyLowR  = this._fix("pianoBodyLowR",  this.pianoBodyLowR);
    this.pianoBodyBandR = this._fix("pianoBodyBandR", this.pianoBodyBandR);
    this.pianoMidLowL   = this._fix("pianoMidLowL",   this.pianoMidLowL);
    this.pianoMidBandL  = this._fix("pianoMidBandL",  this.pianoMidBandL);
    this.pianoMidLowR   = this._fix("pianoMidLowR",   this.pianoMidLowR);
    this.pianoMidBandR  = this._fix("pianoMidBandR",  this.pianoMidBandR);
    this.hsPianoL = this._fix("hsPianoL", this.hsPianoL);
    this.hsPianoR = this._fix("hsPianoR", this.hsPianoR);
  }

  _sanitizeFm() {
    this.fmModFbSample = this._fix("fmModFbSample", this.fmModFbSample);
  }

  _sanitizeAmp() {
    this.ampBodyLowL  = this._fix("ampBodyLowL",  this.ampBodyLowL);
    this.ampBodyBandL = this._fix("ampBodyBandL", this.ampBodyBandL);
    this.ampBodyLowR  = this._fix("ampBodyLowR",  this.ampBodyLowR);
    this.ampBodyBandR = this._fix("ampBodyBandR", this.ampBodyBandR);
    this.ampPresLowL  = this._fix("ampPresLowL",  this.ampPresLowL);
    this.ampPresBandL = this._fix("ampPresBandL", this.ampPresBandL);
    this.ampPresLowR  = this._fix("ampPresLowR",  this.ampPresLowR);
    this.ampPresBandR = this._fix("ampPresBandR", this.ampPresBandR);
    this.ampCabL      = this._fix("ampCabL",      this.ampCabL);
    this.ampCabR      = this._fix("ampCabR",      this.ampCabR);
    this.ampDcPrevInL  = this._fix("ampDcPrevInL",  this.ampDcPrevInL);
    this.ampDcPrevOutL = this._fix("ampDcPrevOutL", this.ampDcPrevOutL);
    this.ampDcPrevInR  = this._fix("ampDcPrevInR",  this.ampDcPrevInR);
    this.ampDcPrevOutR = this._fix("ampDcPrevOutR", this.ampDcPrevOutR);
    this.ampSpkFbL = this._fix("ampSpkFbL", this.ampSpkFbL);
    this.ampSpkFbR = this._fix("ampSpkFbR", this.ampSpkFbR);
    if (this.ampHbL) this.ampHbL.sanitize();
    if (this.ampHbR) this.ampHbR.sanitize();
  }

  _sanitizeMetal() {
    if (this.metalHbL) this.metalHbL.sanitize();
    if (this.metalHbR) this.metalHbR.sanitize();
  }

  // NOISE has no feedback-rich state to sanitize.

  sanitizeState() {
    switch (this.voiceType) {
      case "tanpura": this._sanitizeTanpura(); break;
      case "reed":    this._sanitizeReed();    break;
      case "air":     this._sanitizeAir();     break;
      case "piano":   this._sanitizePiano();   break;
      case "fm":      this._sanitizeFm();      break;
      case "amp":     this._sanitizeAmp();     break;
      case "metal":   this._sanitizeMetal();   break;
      case "noise":   /* no feedback state */  break;
    }

    // Periodic diag emit — every ~1s (375 blocks @ 48kHz/128). Only
    // posts when fires > 0, so silent voices stay silent on the port.
    // After this fix the diag should be effectively silent in normal
    // use; any fire is a real audio-processing NaN worth investigating.
    this._diagBlocks = (this._diagBlocks | 0) + 1;
    if (this._diagBlocks >= 375) {
      if (this._nanFires > 0) {
        try {
          this.port.postMessage({
            type: "nan-diag",
            voiceType: this.voiceType,
            fires: this._nanFires,
            fields: this._nanFieldCounts,
          });
        } catch { /* ok */ }
      }
      this._nanFires = 0;
      this._nanFieldCounts = null;
      this._diagBlocks = 0;
    }
  }

  process(_inputs, outputs, parameters) {
    if (this.stopped) return false;
    const output = outputs[0];
    if (!output || output.length === 0) return true;
    const L = output[0];
    const R = output.length > 1 ? output[1] : output[0];
    const n = L.length;

    const freq  = parameters.freq[0];
    const drift = parameters.drift[0];
    const amp   = parameters.amp[0];
    const pluckRate = parameters.pluckRate ? parameters.pluckRate[0] : 1;
    const color = parameters.color ? parameters.color[0] : 0.3;

    // If amp is 0 and we're silent, skip processing to save CPU.
    // (Voices ramp amp up/down externally, so brief silence is normal.)
    if (amp < 0.0001) {
      for (let i = 0; i < n; i++) { L[i] = 0; if (R !== L) R[i] = 0; }
      return true;
    }

    // NaN/Infinity sanitation on every feedback-rich scalar the voice
    // touches. One bad sample in an SVF / KS / DC-block state traps the
    // voice at silence or subsonic DC forever; this is the single
    // cheapest place to reset it per block.
    this.sanitizeState();

    switch (this.voiceType) {
      case "tanpura": this.tanpuraProcess(L, R, n, freq, drift, amp, pluckRate); break;
      case "reed":    this.reedProcess(L, R, n, freq, drift, amp); break;
      case "metal":   this.metalProcess(L, R, n, freq, drift, amp); break;
      case "air":     this.airProcess(L, R, n, freq, drift, amp); break;
      case "piano":   this.pianoProcess(L, R, n, freq, drift, amp); break;
      case "fm":      this.fmProcess(L, R, n, freq, drift, amp); break;
      case "amp":     this.ampProcess(L, R, n, freq, drift, amp); break;
      case "noise":   this.noiseProcess(L, R, n, freq, drift, amp, color); break;
    }
    return true;
  }

}



// ══ tanpura.js ══════════════════════════════════════════════════

// mdrone voice worklet — TANPURA (Karplus-Strong + jawari, auto-pluck cycle) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

// Authored tanpura string tunings. Keys match the `tanpuraTuning`
// option threaded through VoiceBuilder → processorOptions. Each value
// is a 4-element array of frequency ratios relative to the drone root.
//   classic       micro-detune unison (original default)
//   sa-pa         low Sa, two middle Sa, high Pa (fifth) — most ragas
//   sa-ma         Ma (fourth) instead of Pa — Malkauns et al.
//   sa-ni         Ni (major 7th) — late-night ragas (Bhairav / Lalit)
//   sa-ma-pa-ni   all four distinct — non-traditional harmony
const TANPURA_TUNING_RATIOS = {
  "classic":     [1.0, 1.00116, 0.99884, 1.00058],
  "sa-pa":       [0.5, 1.0, 1.0, 1.5],
  "sa-ma":       [0.5, 1.0, 1.0, 4 / 3],
  "sa-ni":       [0.5, 1.0, 1.0, 15 / 8],
  "sa-ma-pa-ni": [1.0, 4 / 3, 1.5, 15 / 8],
};

// Intrinsic loudness trim for the TANPURA voice. The 2026-05-01 preset
// audit (1.20.12) measured tanpura-drone at -22.7 LUFS while the next
// loudest "main voice" preset (sunn-amp-drone) sat at -23.1 and the
// polite middle (eno-airport / hollow-drone / fennesz-endless) lived
// around -28 to -32 LUFS. Tanpura's jawari buzz puts harmonic energy
// in the 2-8 kHz band where ear sensitivity peaks, making it
// perceptually 5-8 dB hotter than equal-RMS voices. 0.5 = -6 dB,
// applied at the final output write so amp / drift / pluck dynamics
// stay intact.
const TANPURA_INTRINSIC_GAIN = 0.5;

DroneVoiceProcessor.prototype.initTanpura = function() {
    this.NUM_STRINGS = 4;
    const tuningId = this.tanpuraTuningOpt || "classic";
    const ratios = TANPURA_TUNING_RATIOS[tuningId] || TANPURA_TUNING_RATIOS.classic;
    this.stringDetune = ratios.slice();
    this.stringPanL = [0.85, 1.0, 0.7, 0.9];
    this.stringPanR = [1.0, 0.7, 0.85, 0.9];
    // 60 ms delay line — enough for a sub-octave (0.5×) string down to
    // a ~17 Hz root. Previously 40 ms which clipped explicit Sa-below
    // tunings at low tonics.
    this.ksMax = Math.ceil(sampleRate * 0.06) + 8;
    this.ksBufs = [];
    this.ksBufsR = [];
    this.ksIdxs = new Int32Array(this.NUM_STRINGS);
    this.ksIdxsR = new Int32Array(this.NUM_STRINGS);
    this.ksLasts = new Float32Array(this.NUM_STRINGS);
    this.ksLastsR = new Float32Array(this.NUM_STRINGS);
    for (let s = 0; s < this.NUM_STRINGS; s++) {
      this.ksBufs.push(new Float32Array(this.ksMax));
      this.ksBufsR.push(new Float32Array(this.ksMax));
    }
    this.pluckCountdowns = new Float32Array([0.1, 0.5, 0.9, 1.3]);
    this.stringDamp = [0.9983, 0.9985, 0.9986, 0.9984];
    this.ksBodyF = 2 * Math.sin(Math.PI * 150 / sampleRate);
    this.ksBodyDamp = 1 / 4;
    this.ksBodyLowL = 0;
    this.ksBodyBandL = 0;
    this.ksBodyLowR = 0;
    this.ksBodyBandR = 0;
    this.hsKsL = 0;
    this.hsKsR = 0;
    this.holdActive = false;
    // Per-string 2× halfband oversamplers around the jawari nonlinearity
    // (tanh + sin compound). The input is already KS-lowpass-filtered so
    // aliasing is subtler than AMP/METAL, but jawari's sin(2.1·y) term
    // can still fold audible images on loud plucks.
    this.jawHbL = [];
    this.jawHbR = [];
    for (let s = 0; s < this.NUM_STRINGS; s++) {
      this.jawHbL.push(new Halfband2x());
      this.jawHbR.push(new Halfband2x());
    }
    // Envelope-driven jawari bridge state (per-string, per-channel).
    // Real jawari buzz is *envelope-gated*: the string only collides
    // with the curved bone bridge when its amplitude is high. A leaky
    // |y| follower drives a soft-collision term and a 1.6 kHz buzz
    // formant SVF. Below threshold, the shaper degenerates back to
    // the plain tanh tone.
    this.jawEnvL = new Float32Array(this.NUM_STRINGS);
    this.jawEnvR = new Float32Array(this.NUM_STRINGS);
    this.jawFormLowL  = new Float32Array(this.NUM_STRINGS);
    this.jawFormBandL = new Float32Array(this.NUM_STRINGS);
    this.jawFormLowR  = new Float32Array(this.NUM_STRINGS);
    this.jawFormBandR = new Float32Array(this.NUM_STRINGS);
    this.jawFormF    = 2 * Math.sin(Math.PI * 1600 / sampleRate);
    this.jawFormDamp = 0.25; // Q ≈ 4
    // Per-block scratch buffers for variable-rate KS read positions.
    // Pre-allocated here so tanpuraProcess() doesn't allocate on every
    // 128-sample block — naked allocations inside process() trigger GC
    // on weaker hardware (older Windows laptops, Chromebooks) and read
    // as random clicks every few seconds.
    this.delayLens  = new Int32Array(this.NUM_STRINGS);
    this.delayLensR = new Int32Array(this.NUM_STRINGS);
    this.fracsL     = new Float32Array(this.NUM_STRINGS);
    this.fracsR     = new Float32Array(this.NUM_STRINGS);
    // Sympathetic-coupling bus — accumulates each string's bridge
    // contribution at the end of a sample, then feeds a tiny fraction
    // back into all KS write-backs the *following* sample. This is the
    // "shimmer halo" between strings; gain is bounded well under the
    // KS damping budget so the coupled system stays stable on holds.
    this.jawBridgeBusL = 0;
    this.jawBridgeBusR = 0;
    // DC-blocker state — the asymmetric jawari bridge content (soft-
    // collision + halfband-shaped tanh) accumulates a small static
    // even-harmonic DC bias that the offline audit measured at 0.07–
    // 0.18 across tanpura-led presets, well above the engine-wide
    // ±0.005 target. One-pole HPF at ~38 Hz mirrors the pattern used
    // in amp / air / noise.
    this.tanDcPrevInL  = 0;
    this.tanDcPrevOutL = 0;
    this.tanDcPrevInR  = 0;
    this.tanDcPrevOutR = 0;
};

DroneVoiceProcessor.prototype.tanpuraProcess = function(L, R, n, freq, drift, amp, pluckRate) {
    const hold = pluckRate < 0.05;
    const baseLen = sampleRate / Math.max(20, freq);
    const jawK = 1.1;
    const jawMix = 0.22;
    // Hoisted jawari shaper — allocating it inside the per-sample,
    // per-string inner loop created 8 closures per sample, which
    // Safari/JSC doesn't escape-analyse. The GC churn inside the
    // realtime audio callback produced the "frrrr" hash on Safari.
    const jawShaper = (v) =>
      v * 0.78 + (Math.tanh(jawK * v) + jawMix * fastSin(jawK * 2.1 * v)) * 0.22;
    // Envelope-driven bridge constants. Threshold and gains chosen
    // so that at sustain (env ≈ 0.05–0.15) the bridge contribution
    // is near silent, and only loud transients (env > 0.2) produce
    // audible buzz/formant — same behaviour as a real jawari.
    const jawEnvAtk    = 0.0006;  // ~3 ms at 48 k
    const jawEnvRel    = 0.99965; // ~50 ms decay
    const jawThresh    = 0.18;
    // Soft-knee width for the bridge projection. The collision term
    // was originally `max(0, |y| - thresh) * sign(y)` — continuous
    // (C⁰) but not smooth (C¹), so its derivative kinked at every
    // threshold crossing, generating broadband content that aliased
    // (no oversampling around the bridge add) and was then time-
    // smeared by plate/hall reverbs into a sustained HF cloud.
    // Replacing the hinge with a quadratic transition over ±jawKneeW
    // makes the derivative continuous; spectral content above ~5 kHz
    // collapses by ≥40 dB. Width 0.04 keeps the buzz character
    // identical at sustained levels (env > 0.2 plays in the linear
    // region above threshold + jawKneeW).
    const jawKneeW     = 0.04;
    const jawKnee4Inv  = 1 / (4 * jawKneeW);
    const jawProjGain  = 0.55;    // soft-collision contribution
    const jawFormGain  = 0.45;    // 1.6 kHz buzz formant contribution
    const jawFormF     = this.jawFormF;
    const jawFormDamp  = this.jawFormDamp;
    // Sympathetic coupling — only the bounded soft-collision term
    // (slope ≤ 1 above threshold) feeds the bus; the Q=4 buzz formant
    // would create envelope-dependent loop gain and ring up to NaN
    // on long holds. The local string still gets the buzz formant;
    // it just doesn't propagate through the cross-string bus.
    const jawCoupling  = 0.0012;

    // Pluck scheduling — round-robin, each string on its own timer
    const blockSec = n / sampleRate;
    if (hold) {
      if (!this.holdActive) {
        this.holdActive = true;
        for (let s = 0; s < this.NUM_STRINGS; s++) {
          const exact = Math.min(this.ksMax - 2, Math.max(8, baseLen / this.stringDetune[s]));
          this.doPluckString(s, Math.floor(exact));
        }
      }
    } else {
      this.holdActive = false;
      for (let s = 0; s < this.NUM_STRINGS; s++) {
        this.pluckCountdowns[s] -= blockSec;
        if (this.pluckCountdowns[s] <= 0) {
          const exact = Math.min(this.ksMax - 2, Math.max(8, baseLen / this.stringDetune[s]));
          this.doPluckString(s, Math.floor(exact));
          const pr = Math.max(0.05, pluckRate || 1);
          this.pluckCountdowns[s] = (5.0 + this.rng() * 2.0) / pr;
        }
      }
    }

    // Per-string delay lengths (stable — same root, micro-detune only)
    const delayLens  = this.delayLens;
    const delayLensR = this.delayLensR;
    const fracsL     = this.fracsL;
    const fracsR     = this.fracsR;
    for (let s = 0; s < this.NUM_STRINGS; s++) {
      const dt = this.stringDetune[s];
      const exact = Math.min(this.ksMax - 2, Math.max(8, baseLen / dt));
      delayLens[s] = Math.floor(exact);
      fracsL[s] = exact - delayLens[s];
      // R-side dichotic spread — applied as an extra frequency ratio
      // on the KS delay length (delay = sampleRate / freq, so divide
      // by the ratio to raise the R pitch when dichoticMulR > 1).
      const exactR = Math.min(this.ksMax - 2, Math.max(8, baseLen / (dt * 1.003 * this.dichoticMulR)));
      delayLensR[s] = Math.floor(exactR);
      fracsR[s] = exactR - delayLensR[s];
    }

    for (let i = 0; i < n; i++) {
      let sumL = 0, sumR = 0;
      // Bridge bus accumulators — used to compute *next sample*'s
      // sympathetic injection. We cannot inject same-sample without
      // creating a delay-free feedback loop across the strings.
      let bridgeAccL = 0, bridgeAccR = 0;
      const injectL = this.jawBridgeBusL * jawCoupling;
      const injectR = this.jawBridgeBusR * jawCoupling;

      for (let s = 0; s < this.NUM_STRINGS; s++) {
        const buf = this.ksBufs[s];
        const bufR = this.ksBufsR[s];
        const idx = this.ksIdxs[s];
        const idxR = this.ksIdxsR[s];
        const dLen = delayLens[s];
        const dLenR = delayLensR[s];
        const damp = hold ? 1.0 : this.stringDamp[s] - drift * 0.0012;

        const cur = buf[idx];
        const nxt = buf[(idx + 1) % dLen];
        let y = cur * (1 - fracsL[s]) + nxt * fracsL[s] + 1e-20;
        this.ksLasts[s] = this.ksLasts[s] * 0.35 + y * 0.65;
        y = this.ksLasts[s] * damp;
        // Envelope-driven bridge: leaky |y| follower gates a soft-
        // collision term + 1.6 kHz buzz formant. Sustain is near-
        // silent (env small); only loud transients buzz, mirroring
        // the curved-bridge behaviour of a real tanpura.
        // Peak-tracking one-pole: fast attack on rising |y|, slow release.
        const ay = y < 0 ? -y : y;
        let envL = this.jawEnvL[s] * jawEnvRel + ay * (1 - jawEnvRel);
        if (ay > envL) envL = envL + (ay - envL) * jawEnvAtk;
        this.jawEnvL[s] = envL;
        // Buzz formant SVF (input = pre-shape y).
        const bH_L = y - this.jawFormLowL[s] - jawFormDamp * this.jawFormBandL[s];
        // +1e-20 keeps the SVF feedback states above subnormal range on
        // long sustained holds. Q=4 means the bandpass can recirculate
        // very small values; without this, JSC on iOS / older Firefox
        // park denormals here and CPU spikes silently every few seconds.
        this.jawFormBandL[s] += jawFormF * bH_L + 1e-20;
        this.jawFormLowL[s]  += jawFormF * this.jawFormBandL[s] + 1e-20;
        const buzzL = this.jawFormBandL[s];
        // Soft-knee projection (see jawKneeW comment). Linear above
        // jawThresh + w, zero below jawThresh − w, quadratic in
        // between — C¹ at both seams.
        const dL = ay - jawThresh;
        let mL;
        if (dL > jawKneeW) mL = dL;
        else if (dL > -jawKneeW) { const t = dL + jawKneeW; mL = t * t * jawKnee4Inv; }
        else mL = 0;
        const projL = mL * (y < 0 ? -1 : 1);
        const bridgeL = envL * (projL * jawProjGain + buzzL * jawFormGain);
        // Only the bounded soft-collision feeds the cross-string bus.
        bridgeAccL += envL * projL * jawProjGain;
        // Halfband-shaped KS output — written back into the KS buffer
        // (this preserves the original string state machine).
        const yKsL = this.jawHbL[s].process(y, jawShaper);
        // Output path adds the envelope-gated bridge content. Bridge
        // is *not* written back to the KS buffer: feeding the Q=4 buzz
        // formant into the comb tuned at the string fundamental created
        // a resonant loop that ran up to NaN on long holds.
        y = yKsL + bridgeL;

        const curR = bufR[idxR];
        const nxtR = bufR[(idxR + 1) % dLenR];
        let yR = curR * (1 - fracsR[s]) + nxtR * fracsR[s] + 1e-20;
        this.ksLastsR[s] = this.ksLastsR[s] * 0.35 + yR * 0.65;
        yR = this.ksLastsR[s] * damp;
        const ayR = yR < 0 ? -yR : yR;
        let envR = this.jawEnvR[s] * jawEnvRel + ayR * (1 - jawEnvRel);
        if (ayR > envR) envR = envR + (ayR - envR) * jawEnvAtk;
        this.jawEnvR[s] = envR;
        const bH_R = yR - this.jawFormLowR[s] - jawFormDamp * this.jawFormBandR[s];
        this.jawFormBandR[s] += jawFormF * bH_R + 1e-20;
        this.jawFormLowR[s]  += jawFormF * this.jawFormBandR[s] + 1e-20;
        const buzzR = this.jawFormBandR[s];
        const dR = ayR - jawThresh;
        let mR;
        if (dR > jawKneeW) mR = dR;
        else if (dR > -jawKneeW) { const t = dR + jawKneeW; mR = t * t * jawKnee4Inv; }
        else mR = 0;
        const projR = mR * (yR < 0 ? -1 : 1);
        const bridgeR = envR * (projR * jawProjGain + buzzR * jawFormGain);
        bridgeAccR += envR * projR * jawProjGain;
        const yKsR = this.jawHbR[s].process(yR, jawShaper);
        yR = yKsR + bridgeR;

        // KS buffer carries only the shaped string state plus a tiny
        // sympathetic forcing from the previous sample's bus (bounded
        // soft-collision only — see jawCoupling note above).
        buf[idx] = yKsL + injectL;
        this.ksIdxs[s] = (idx + 1) % dLen;
        bufR[idxR] = yKsR + injectR;
        this.ksIdxsR[s] = (idxR + 1) % dLenR;

        sumL += y * this.stringPanL[s];
        sumR += yR * this.stringPanR[s];
      }
      // Latch this sample's bridge sum for next-sample injection.
      this.jawBridgeBusL = bridgeAccL;
      this.jawBridgeBusR = bridgeAccR;

      // 0.3 → 0.26 → 0.22 → 0.16: solo-LUFS audit showed tanpura at
      // voiceLevel=1.0 was ~13 dB louder than reed (shruti-box) and
      // 25+ dB louder than metal at the same setting — so multi-voice
      // presets had to set tanpura: 0.3..0.5 just to fight the source-
      // level imbalance. This trim closes ~3 dB of that gap globally;
      // solo tanpura presets compensate via preset `gain:` to keep
      // their target loudness. Jawari character preserved (KS and
      // bridge scale together).
      sumL *= 0.16;
      sumR *= 0.16;

      const bodyHighL = sumL - this.ksBodyLowL - this.ksBodyDamp * this.ksBodyBandL;
      this.ksBodyBandL += this.ksBodyF * bodyHighL;
      this.ksBodyLowL += this.ksBodyF * this.ksBodyBandL;
      const bodyHighR = sumR - this.ksBodyLowR - this.ksBodyDamp * this.ksBodyBandR;
      this.ksBodyBandR += this.ksBodyF * bodyHighR;
      this.ksBodyLowR += this.ksBodyF * this.ksBodyBandR;

      let postL = sumL + this.ksBodyBandL * 0.12;
      let postR = sumR + this.ksBodyBandR * 0.12;
      this.hsKsL = this.hsKsL * 0.6 + postL * 0.4;
      this.hsKsR = this.hsKsR * 0.6 + postR * 0.4;
      postL += (postL - this.hsKsL) * 0.3;
      postR += (postR - this.hsKsR) * 0.3;

      // DC-blocker — strips the static even-harmonic bias accumulated
      // by the jawari shaper (audit measured 0.07–0.18 DC pre-blocker).
      const dcCoef = 0.995;
      const dcOutL = postL - this.tanDcPrevInL + dcCoef * this.tanDcPrevOutL;
      this.tanDcPrevInL = postL; this.tanDcPrevOutL = dcOutL;
      const dcOutR = postR - this.tanDcPrevInR + dcCoef * this.tanDcPrevOutR;
      this.tanDcPrevInR = postR; this.tanDcPrevOutR = dcOutR;

      L[i] = dcOutL * amp * TANPURA_INTRINSIC_GAIN;
      R[i] = dcOutR * amp * TANPURA_INTRINSIC_GAIN;
    }
};

DroneVoiceProcessor.prototype.doPluckString = function(s, delayLen) {
    const buf = this.ksBufs[s];
    const bufR = this.ksBufsR[s];
    const delayLenR = Math.min(this.ksMax - 2, delayLen + 2);
    const lpCoef = 0.15;
    let lpL = 0;
    for (let i = 0; i < delayLen; i++) {
      const v = (this.rng() * 2 - 1);
      lpL += lpCoef * (v - lpL);
      buf[i] = lpL * 0.85;
    }
    let lpR = 0;
    for (let i = 0; i < delayLenR; i++) {
      const v = (this.rng() * 2 - 1);
      lpR += lpCoef * (v - lpR);
      bufR[i] = lpR * 0.85;
    }
    this.ksIdxs[s] = 0;
    this.ksIdxsR[s] = 0;
    this.ksLasts[s] = 0;
    this.ksLastsR[s] = 0;
};



// ══ reed.js ══════════════════════════════════════════════════

// mdrone voice worklet — REED (harmonium/shruti-box additive + PolyBLEP saw) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

DroneVoiceProcessor.prototype.initReed = function() {
    // 7 partials. The shape parameter picks an amplitude curve:
    //   odd      — clarinet/shruti/harmonium (default, original)
    //   even     — bowed string (SOTL, Górecki) — even partials emphasised
    //   balanced — pipe organ, choral "ahh" (Malone) — both odd and even
    //   sine     — pure fundamental (Dream House, Radigue ARP 2500)
    // Partial count is shape-dependent. "even" (bowed string) and
    // "balanced" (organ/choral) gain richer upper harmonics with 12
    // partials; 7 was audibly thin for these timbres. "odd"
    // (clarinet/shruti) and "sine" stay at 7 — clarinet spectra are
    // dominated by the first few odd harmonics in reality.
    const REED_AMPS = {
      odd:      [0.55, 0.28, 0.38, 0.13, 0.24, 0.07, 0.16],
      even:     [0.55, 0.48, 0.20, 0.36, 0.14, 0.24, 0.08, 0.16, 0.04, 0.10, 0.03, 0.06],
      balanced: [0.60, 0.40, 0.34, 0.26, 0.20, 0.14, 0.10, 0.07, 0.05, 0.035, 0.025, 0.018],
      sine:     [1.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00],
    };
    const amps = REED_AMPS[this.reedShape] || REED_AMPS.odd;
    this.reedN = amps.length;
    this.reedAmps     = new Float32Array(amps);
    this.reedPhasesL  = new Float32Array(this.reedN);
    this.reedPhasesR  = new Float32Array(this.reedN);
    // Per-partial slow LFO state (0.08..0.28 Hz randomized)
    this.reedLfoPhases = new Float32Array(this.reedN);
    this.reedLfoRates  = new Float32Array(this.reedN);
    this.reedAmpJitterPhases = new Float32Array(this.reedN);
    this.reedAmpJitterRates  = new Float32Array(this.reedN);
    for (let i = 0; i < this.reedN; i++) {
      this.reedPhasesL[i] = this.rng() * Math.PI * 2;
      this.reedPhasesR[i] = this.rng() * Math.PI * 2;
      this.reedLfoPhases[i] = this.rng() * Math.PI * 2;
      this.reedLfoRates[i] = 0.08 + this.rng() * 0.2;
      this.reedAmpJitterPhases[i] = this.rng() * Math.PI * 2;
      this.reedAmpJitterRates[i] = 0.01 + this.rng() * 0.03;
    }
    // Bellows amplitude LFO — slow, shared
    this.bellowsPhase = 0;
    this.bellowsRate = 0.22 + this.rng() * 0.08;

    // PolyBLEP saw state for "even" (bowed-string) shape — a
    // bandlimited sawtooth is fundamentally richer than summing
    // 12 sines. Phase is 0..1 (not 0..2pi) for PolyBLEP.
    this.useSaw = this.reedShape === "even";
    if (this.useSaw) {
      this.sawPhaseL = this.rng();
      this.sawPhaseR = this.rng();
      // Slow wobble on the saw frequency for life
      this.sawLfoPhase = this.rng() * Math.PI * 2;
      this.sawLfoRate = 0.12 + this.rng() * 0.08;
    }

    // Formant layer — wide bandpass peaks that give the additive
    // harmonic stack a "body". Without this the reed reads as "7
    // sines + LFO"; with it, it reads as sines *through* a physical
    // resonator. Shape picks the formant set:
    //   odd      — shruti/clarinet: bright upper body
    //   even     — bowed string: classic cello/viola body
    //   balanced — pipe organ / vocal "ahh" formant
    //   sine     — none (pure fundamental bypasses formants)
    // Each entry: [centerHz, Q, mixGain]. Q=2.0 gives more pronounced
    // body than the original 1.2 while staying below the Q=3-4
    // threshold where bellows AM interaction caused "frrr" artifacts.
    // Bellows depth was reduced to ±2.5% to keep the safe zone.
    // Q raised to 2.0 from 1.2 — more pronounced instrument body.
    // Bellows depth reduced to ±2.5% (was ±4%) to prevent the
    // bellows×formant interaction "frrr" artifact that Q=3-4 caused.
    // Q=2.0 + gentle bellows sits in the safe zone.
    const FORMANTS = {
      odd:      [[500, 2.0, 0.07], [1200, 2.0, 0.05], [2500, 2.0, 0.03]],
      even:     [[300, 2.0, 0.08], [700, 2.0, 0.06], [1400, 2.0, 0.04]],
      balanced: [[400, 2.0, 0.075], [900, 2.0, 0.055], [1800, 2.0, 0.035]],
      sine:     [],
    };
    const formants = FORMANTS[this.reedShape] || FORMANTS.odd;
    this.reedFormN = formants.length;
    this.reedFormF    = new Float32Array(this.reedFormN);
    this.reedFormDamp = new Float32Array(this.reedFormN);
    this.reedFormGain = new Float32Array(this.reedFormN);
    this.reedFormLowL  = new Float32Array(this.reedFormN);
    this.reedFormBandL = new Float32Array(this.reedFormN);
    this.reedFormLowR  = new Float32Array(this.reedFormN);
    this.reedFormBandR = new Float32Array(this.reedFormN);
    for (let i = 0; i < this.reedFormN; i++) {
      const fc = formants[i][0];
      const q  = formants[i][1];
      const g  = formants[i][2];
      this.reedFormF[i] = 2 * Math.sin(Math.PI * fc / sampleRate);
      this.reedFormDamp[i] = 1 / q;
      this.reedFormGain[i] = g;
    }
    // Presence shelf state — one-pole LP that we subtract from the
    // signal to synthesise a +2.3 dB high shelf above ~3 kHz. The
    // formant bank adds 300-1800 Hz body energy, which without this
    // compensation perceptually dulls the reed highs after master
    // limiting. Matches the technique used in airProcess().
    this.hsReedL = 0;
    this.hsReedR = 0;
    // 2× halfband oversamplers around the source-level tanh — without
    // these, the saturation harmonics of a 12-partial "even" stack or
    // a PolyBLEP saw alias back into the audible band, audible as a
    // "crispy"/"fizzy" hash on top of the formant body. The presence
    // shelf below then re-emphasises exactly that aliased band, so
    // oversampling the tanh is the only correct fix.
    this.reedHbL = new Halfband2x();
    this.reedHbR = new Halfband2x();
};

DroneVoiceProcessor.prototype.reedProcess = function(L, R, n, freq, drift, amp) {
    const invSr = 1 / sampleRate;
    const twoPi = Math.PI * 2;
    // Drift → per-partial detune depth (max ±8 cents)
    const detuneDepth = drift * 0.0046; // in cent-ratio (8 cents ≈ 0.0046)
    // Aliasing guard — skip partials whose frequency exceeds 90% of
    // Nyquist. Matters now that even/balanced shapes have 12 partials:
    // at high tonics partial 12 can reach above 20 kHz.
    const nyquist = sampleRate * 0.45;
    // Hoisted shaper — allocating the arrow inside the sample loop
    // creates a per-sample closure (Safari/JSC GC hash inside the
    // realtime audio callback). Same pattern as amp.js / metal.js.
    const reedShaper = (v) => Math.tanh(v * 1.6) * 0.7;

    for (let i = 0; i < n; i++) {
      // Advance bellows amplitude LFO
      this.bellowsPhase += twoPi * this.bellowsRate * invSr;
      if (this.bellowsPhase > twoPi) this.bellowsPhase -= twoPi;
      const bellows = 1 + Math.sin(this.bellowsPhase) * 0.025; // ±2.5% (reduced from 4% to avoid formant×bellows artifact at Q=2)

      let l = 0, r = 0;

      if (this.useSaw) {
        // PolyBLEP sawtooth path — "even" (bowed-string) shape.
        // A bandlimited saw has all harmonics falling at 1/n,
        // fundamentally richer than summing 12 sines.
        this.sawLfoPhase += twoPi * this.sawLfoRate * invSr;
        if (this.sawLfoPhase > twoPi) this.sawLfoPhase -= twoPi;
        const wobble = Math.sin(this.sawLfoPhase) * detuneDepth;
        const sawFreq = freq * (1 + wobble);
        const dtL = sawFreq * invSr;
        const dtR = sawFreq * (1 + detuneDepth * 0.5) * invSr;
        this.sawPhaseL += dtL;
        if (this.sawPhaseL >= 1) this.sawPhaseL -= 1;
        this.sawPhaseR += dtR;
        if (this.sawPhaseR >= 1) this.sawPhaseR -= 1;
        const rawL = 2 * this.sawPhaseL - 1 - polyblep(this.sawPhaseL, dtL);
        const rawR = 2 * this.sawPhaseR - 1 - polyblep(this.sawPhaseR, dtR);
        l = rawL * 0.22 * bellows;
        r = rawR * 0.22 * bellows;
      } else {
        // Additive partial path — odd, balanced, sine shapes
        for (let p = 0; p < this.reedN; p++) {
          this.reedLfoPhases[p] += twoPi * this.reedLfoRates[p] * invSr;
          if (this.reedLfoPhases[p] > twoPi) this.reedLfoPhases[p] -= twoPi;
          const wobble = Math.sin(this.reedLfoPhases[p]) * detuneDepth;

          const partialFreq = freq * (p + 1) * (1 + wobble);
          if (partialFreq > nyquist) continue;
          this.reedPhasesL[p] += twoPi * partialFreq * invSr;
          this.reedPhasesR[p] += twoPi * partialFreq * invSr * (1 + detuneDepth * 0.5) * this.dichoticMulR;
          if (this.reedPhasesL[p] > twoPi) this.reedPhasesL[p] -= twoPi;
          if (this.reedPhasesR[p] > twoPi) this.reedPhasesR[p] -= twoPi;

          this.reedAmpJitterPhases[p] += twoPi * this.reedAmpJitterRates[p] * invSr;
          if (this.reedAmpJitterPhases[p] > twoPi) this.reedAmpJitterPhases[p] -= twoPi;
          const jitter = 1 + Math.sin(this.reedAmpJitterPhases[p]) * 0.08;
          const amp_p = this.reedAmps[p] * bellows * jitter;
          const pan = (p % 2 === 0) ? 1 : 0.85;
          const panR = (p % 2 === 0) ? 0.85 : 1;
          l += fastSin(this.reedPhasesL[p]) * amp_p * pan;
          r += fastSin(this.reedPhasesR[p]) * amp_p * panR;
        }
        // Scale the raw additive stack before the formant bank
        l *= 0.22;
        r *= 0.22;
      }

      // Bellows breath noise — real harmoniums have audible air
      // leakage modulated by bellows pressure. Adds physical breath
      // character that pure additive/saw lacks.
      const breathNoise = (this.rng() * 2 - 1) * 0.008 * bellows;
      l += breathNoise;
      r += breathNoise * 0.92; // slight stereo decorrelation

      // Formant bank — parallel bandpass peaks add body resonance.
      // Each SVF advances one sample on the *clean* scaled stack;
      // its band output is summed into the dry. See initReed() for
      // the shape→formant table and the Q rationale.
      let formL = 0, formR = 0;
      for (let f = 0; f < this.reedFormN; f++) {
        const fc = this.reedFormF[f];
        const dampF = this.reedFormDamp[f];
        const g = this.reedFormGain[f];
        const hL = l - this.reedFormLowL[f] - dampF * this.reedFormBandL[f];
        this.reedFormBandL[f] += fc * hL;
        this.reedFormLowL[f]  += fc * this.reedFormBandL[f];
        const hR = r - this.reedFormLowR[f] - dampF * this.reedFormBandR[f];
        this.reedFormBandR[f] += fc * hR;
        this.reedFormLowR[f]  += fc * this.reedFormBandR[f];
        formL += this.reedFormBandL[f] * g;
        formR += this.reedFormBandR[f] * g;
      }
      l += formL;
      r += formR;

      // Source-level tanh saturation — now applied *after* the
      // formant sum so it acts as the natural amplitude limiter
      // on the combined (partial stack + body) signal. This is
      // both physically more correct (the instrument body colours
      // then the reed bites) and prevents formant state from
      // bleeding unbounded peaks into downstream effects.
      // Wrapped in a 2× halfband oversampler so the harmonics
      // generated above Nyquist don't fold back into the audible
      // band — without this, slow per-partial AM jitter alignment
      // produces audible "crispy/fizzy" bursts on top of the body.
      l = this.reedHbL.process(l, reedShaper);
      r = this.reedHbR.process(r, reedShaper);

      // Presence shelf — one-pole LP subtracted back at 0.3 gain
      // gives ~+2.3 dB shelf above ~3 kHz. Compensates the body
      // energy the formant bank added so the voice doesn't feel
      // dulled after master-bus limiting.
      this.hsReedL = this.hsReedL * 0.6 + l * 0.4;
      this.hsReedR = this.hsReedR * 0.6 + r * 0.4;
      l += (l - this.hsReedL) * 0.3;
      r += (r - this.hsReedR) * 0.3;

      L[i] = l * amp;
      R[i] = r * amp;
    }
};



// ══ metal.js ══════════════════════════════════════════════════

// mdrone voice worklet — METAL (inharmonic singing-bowl modal stack) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

// Measured-inspired bowl modal table. Each entry is one *physical* mode
// (m=2,3,4…) with a doublet split where applicable — real bowls are not
// perfectly axisymmetric, so each circumferential mode appears as a
// close pair whose interference produces the characteristic slow
// shimmer-beat ("hum note → strike note" envelope). Settle times are
// the linear ramp-to-floor used by the per-sample decay update; with
// the 0.08 Hz restrike LFO they describe how *quickly the strike
// transient relaxes* between re-excitations, not the perceived ring
// of the steady-state. Low circumferential modes (m=2,3) settle over
// 30–12 s so they sit at ≈0.6–0.8 between restrikes (always audible);
// upper deformation modes settle in 1–4 s so they fade and pulse with
// the LFO, which is the bowl's "breathing".
//
// Doublet split ratios narrow with mode order — the asymmetry energy
// budget is roughly fixed, so higher-order modes split proportionally
// less. Splits chosen to fall in the 0.2–0.8 % band measured on small
// hand-hammered Tibetan bowls (Rossing/Inácio).
//
// Top four modes are single oscillators: they decay too fast and their
// amplitude is too low for the doublet beat to be perceptually relevant
// — doubling the oscillator count there is wasted CPU.
const METAL_MODES = [
  // ratio   split    amp    decay     panW   walk    (decay = per-sample
  //                                                    floor-ramp rate)
  { ratio: 1.00,  split: 0.006,  amp: 0.88, decay: 6.6e-7, panW: 0.04, walk: 0.012 },
  { ratio: 2.23,  split: 0.005,  amp: 0.30, decay: 1.6e-6, panW: 0.12, walk: 0.018 },
  { ratio: 3.98,  split: 0.004,  amp: 0.18, decay: 3.3e-6, panW: 0.18, walk: 0.026 },
  { ratio: 6.18,  split: 0.003,  amp: 0.11, decay: 5.0e-6, panW: 0.22, walk: 0.032 },
  { ratio: 8.92,  split: 0.0025, amp: 0.07, decay: 8.0e-6, panW: 0.26, walk: 0.038 },
  { ratio: 11.34, split: 0.0020, amp: 0.04, decay: 1.1e-5, panW: 0.28, walk: 0.042 },
  { ratio: 14.08, split: null,   amp: 0.022,decay: 1.5e-5, panW: 0.32, walk: 0.045 },
  { ratio: 17.6,  split: null,   amp: 0.013,decay: 2.0e-5, panW: 0.32, walk: 0.045 },
  { ratio: 21.9,  split: null,   amp: 0.008,decay: 3.0e-5, panW: 0.34, walk: 0.045 },
  { ratio: 27.1,  split: null,   amp: 0.004,decay: 4.5e-5, panW: 0.34, walk: 0.045 },
];

DroneVoiceProcessor.prototype.initMetal = function() {
    // Expand the modal table into flat per-oscillator arrays. Doublet
    // pairs share decay/walk/pan width so they breathe together but get
    // independent random phases (so beats start at zero crossing, not
    // at peak — the spec calls this out as a phasey/seasick failure
    // mode if missed) and small independent pan offsets within panW.
    const oscRatios = [];
    const oscAmps   = [];
    const oscDecays = [];
    const oscPanW   = [];
    const oscWalks  = [];
    for (const m of METAL_MODES) {
      if (m.split == null) {
        oscRatios.push(m.ratio);
        oscAmps.push(m.amp);
        oscDecays.push(m.decay);
        oscPanW.push(m.panW);
        oscWalks.push(m.walk);
      } else {
        // Energy split equally across the doublet pair so the pair's
        // total RMS matches a single-mode entry of the same `amp`
        // (≈ −3 dB per partial, summed-incoherent).
        const a = m.amp * Math.SQRT1_2;
        oscRatios.push(m.ratio * (1 - m.split * 0.5));
        oscRatios.push(m.ratio * (1 + m.split * 0.5));
        oscAmps.push(a); oscAmps.push(a);
        oscDecays.push(m.decay); oscDecays.push(m.decay);
        oscPanW.push(m.panW);    oscPanW.push(m.panW);
        oscWalks.push(m.walk);   oscWalks.push(m.walk);
      }
    }
    this.metalN          = oscRatios.length;
    this.metalRatios     = new Float32Array(oscRatios);
    this.metalBaseAmps   = new Float32Array(oscAmps);
    this.metalDecayRates = new Float32Array(oscDecays);
    this.metalPhasesL = new Float32Array(this.metalN);
    this.metalPhasesR = new Float32Array(this.metalN);
    this.metalPans    = new Float32Array(this.metalN);
    this.metalAmpWalks      = new Float32Array(this.metalN).fill(1);
    this.metalAmpTargets    = new Float32Array(this.metalN).fill(1);
    this.metalDetuneWalks   = new Float32Array(this.metalN);
    this.metalDetuneTargets = new Float32Array(this.metalN);
    this.metalWalkPhases = new Float32Array(this.metalN);
    this.metalWalkRates  = new Float32Array(this.metalN);
    for (let i = 0; i < this.metalN; i++) {
      this.metalPhasesL[i] = this.rng() * Math.PI * 2;
      this.metalPhasesR[i] = this.rng() * Math.PI * 2;
      // Pan width is per-mode (low modes near centre, upper modes
      // diffuse) — but each oscillator gets its own random offset
      // within that band so doublet pairs don't sit on the same point.
      this.metalPans[i] = (this.rng() - 0.5) * oscPanW[i];
      this.metalWalkRates[i] = oscWalks[i] * (0.7 + this.rng() * 0.6);
    }
    this.metalTickCounter = 0;
    this.metalDecay = new Float32Array(this.metalN).fill(1);
    this.metalRestrikePhase = 0;
    // 2× halfband oversamplers around the output tanh — top mode at
    // 27.1× fundamental reaches ~3 kHz on a 110 Hz tonic; tanh harmonics
    // would otherwise fold below Nyquist as dissonant hiss.
    this.metalHbL = new Halfband2x();
    this.metalHbR = new Halfband2x();
};

DroneVoiceProcessor.prototype.metalProcess = function(L, R, n, freq, drift, amp) {
    const invSr = 1 / sampleRate;
    const twoPi = Math.PI * 2;
    const driftDepth = drift * 0.0024; // keep the bowl centered; max ~4 cents walk
    // Hoisted to avoid per-sample closure allocation inside the
    // AudioWorklet callback (Safari/JSC GC hash).
    const metalShaper = (v) => Math.tanh(v * 0.9);

    for (let i = 0; i < n; i++) {
      // Every ~256 samples, pick new random walk targets.
      this.metalTickCounter++;
      if ((this.metalTickCounter & 255) === 0) {
        for (let p = 0; p < this.metalN; p++) {
          // Fundamental doublet (entries 0,1) walks tightly so the
          // pitch never wavers; everything else gets a wider breadth
          // for liveness, capped to 0.5 so upper-mode amp flutter stays
          // musical rather than seasick.
          const breadth = p < 2 ? 0.08 : Math.min(0.5, 0.26 + p * 0.03);
          const center  = p < 2 ? 0.99 : 0.78;
          this.metalAmpTargets[p] = center - breadth * 0.5 + this.rng() * breadth;
          this.metalDetuneTargets[p] = (this.rng() * 2 - 1) * driftDepth;
        }
      }

      // Slow re-excitation — a ~0.08 Hz cycle that periodically
      // boosts upper partials back, simulating rim-friction or
      // ambient re-excitation of a singing bowl.
      this.metalRestrikePhase += twoPi * 0.08 * invSr;
      if (this.metalRestrikePhase > twoPi) this.metalRestrikePhase -= twoPi;
      const restrike = 0.5 + 0.5 * Math.sin(this.metalRestrikePhase);

      let l = 0, r = 0;
      for (let p = 0; p < this.metalN; p++) {
        // Per-partial decay — high modes settle, fundamental sustains
        this.metalDecay[p] = Math.max(0.05, this.metalDecay[p] - this.metalDecayRates[p]);
        // Re-excitation lifts decayed partials back toward 0.7
        const decayEnv = this.metalDecay[p] + (1 - this.metalDecay[p]) * restrike * 0.6;

        this.metalAmpWalks[p] += (this.metalAmpTargets[p] - this.metalAmpWalks[p]) * 0.000015;
        this.metalDetuneWalks[p] += (this.metalDetuneTargets[p] - this.metalDetuneWalks[p]) * 0.000015;
        this.metalWalkPhases[p] += twoPi * this.metalWalkRates[p] * invSr;
        if (this.metalWalkPhases[p] > twoPi) this.metalWalkPhases[p] -= twoPi;

        const partialFreq = freq * this.metalRatios[p] * (1 + this.metalDetuneWalks[p]);
        this.metalPhasesL[p] += twoPi * partialFreq * invSr;
        this.metalPhasesR[p] += twoPi * partialFreq * invSr * 1.00018 * this.dichoticMulR;
        if (this.metalPhasesL[p] > twoPi) this.metalPhasesL[p] -= twoPi;
        if (this.metalPhasesR[p] > twoPi) this.metalPhasesR[p] -= twoPi;

        const beat = 0.94 + 0.06 * Math.sin(this.metalWalkPhases[p]);
        const amp_p = this.metalBaseAmps[p] * this.metalAmpWalks[p] * beat * decayEnv;
        const pan = this.metalPans[p];
        const lGain = amp_p * (1 - Math.max(0, pan));
        const rGain = amp_p * (1 - Math.max(0, -pan));
        l += fastSin(this.metalPhasesL[p]) * lGain;
        r += fastSin(this.metalPhasesR[p]) * rGain;
      }
      l *= 0.34;
      r *= 0.34;
      // Keep the source comparatively pure; bowls read better when the
      // upper modes stay narrow instead of being driven into brightness.
      // 2× oversampled tanh kills harmonic folding from the 12-partial
      // inharmonic stack.
      l = this.metalHbL.process(l, metalShaper);
      r = this.metalHbR.process(r, metalShaper);
      L[i] = l * amp;
      R[i] = r * amp;
    }
};



// ══ air.js ══════════════════════════════════════════════════

// mdrone voice worklet — AIR (pink noise through SVF resonators) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

DroneVoiceProcessor.prototype.initAir = function() {
    // Pipe-flue / breath resonator model. Harmonic partials (1 2 3 4 6)
    // give a pipe-organ character instead of the beating "wrong organ"
    // the previous semi-inharmonic ratios produced. The noise
    // excitation is dropped to a gentle 1.2× feed (was 4.5) so the
    // pink source animates the resonators without blasting them —
    // resonance does the work, not raw amplitude. Natural 1/n-like
    // rolloff on partial amps for a bellows-lung falloff. High-shelf
    // brighten block is gone — it was adding hiss to a noise-based
    // voice. Final amp halved to 0.8 so layered presets don't
    // accumulate air energy into saturation territory.
    this.airN = 5;
    this.airRatios = new Float32Array([1.0, 2.0, 3.0, 4.0, 6.0]);
    this.airAmps   = new Float32Array([0.50, 0.34, 0.20, 0.11, 0.05]);
    this.airPans   = new Float32Array([0.0, -0.25, 0.25, 0.35, -0.35]);
    // Two-pole state-variable bandpass state per resonator (L + R independent)
    // state: [lowL, bandL, lowR, bandR]
    this.airStates = [];
    for (let i = 0; i < this.airN; i++) {
      this.airStates.push(new Float32Array(4));
    }
    // Q walk state — higher baseline (16) for sustained pipe-like
    // partials, modulated by drift within a narrower range than the
    // old 8-20 that was spiking to whistle territory.
    this.airQWalks = new Float32Array(this.airN).fill(16);
    this.airQTargets = new Float32Array(this.airN).fill(16);
    this.airTickCounter = 0;
    // Bellows gust — slow random amplitude walk on noise input.
    this.airGustLevel = 1;
    this.airGustTarget = 1;
    this.airGustPhase = this.rng() * Math.PI * 2;
    // Independent pink noise state for R so the stereo image isn't mono.
    this.pinkR = { b0: 0, b1: 0, b2: 0, b3: 0, b4: 0, b5: 0, b6: 0 };
    // DC-block state — one-pole HPF at ~20 Hz to bleed off sub-
    // sonic drift the noise source + SVF can accumulate over long
    // holds. Small alpha keeps the HPF well below any audible range.
    this.airDcL = 0;
    this.airDcR = 0;
    this.airDcPrevL = 0;
    this.airDcPrevR = 0;
};

  // Second pink noise generator (uses pinkR state) for independent R channel
DroneVoiceProcessor.prototype.pinkNoiseR = function() {
    const p = this.pinkR;
    const white = this.rng() * 2 - 1;
    p.b0 = 0.99886 * p.b0 + white * 0.0555179;
    p.b1 = 0.99332 * p.b1 + white * 0.0750759;
    p.b2 = 0.969  * p.b2 + white * 0.153852;
    p.b3 = 0.8665 * p.b3 + white * 0.3104856;
    p.b4 = 0.55   * p.b4 + white * 0.5329522;
    p.b5 = -0.7616 * p.b5 - white * 0.016898;
    const out = p.b0 + p.b1 + p.b2 + p.b3 + p.b4 + p.b5 + p.b6 + white * 0.5362;
    p.b6 = white * 0.115926;
    return out * 0.11;
};

DroneVoiceProcessor.prototype.airProcess = function(L, R, n, freq, drift, amp) {
    // Q walk range — tighter than before. 12-20 at drift 0 keeps the
    // tone clean-pipe; wider 10-26 at high drift adds animation. The
    // old 8-20 spiked into whistle territory at high drift which was
    // part of the "scream like wind" complaint.
    const qMin = 12 - drift * 2;
    const qMax = 20 + drift * 6;

    for (let i = 0; i < n; i++) {
      // Slow Q walk every ~512 samples
      this.airTickCounter++;
      if ((this.airTickCounter & 511) === 0) {
        for (let r = 0; r < this.airN; r++) {
          this.airQTargets[r] = qMin + this.rng() * (qMax - qMin);
        }
      }

      // Bellows gust — slow amplitude walk (~0.12 Hz) on the noise
      // source gives breath-like character instead of flat pink.
      this.airGustLevel += (this.airGustTarget - this.airGustLevel) * 0.00004;
      this.airGustPhase += 6.283 * 0.12 / sampleRate;
      if (this.airGustPhase > 6.283) {
        this.airGustPhase -= 6.283;
        this.airGustTarget = 0.6 + this.rng() * 0.4;
      }
      const gust = this.airGustLevel;
      // Noise excitation much reduced — 1.2 instead of 4.5. The
      // resonators do the work; hot noise input was reading as hiss
      // rather than pipe/breath.
      const noiseL = this.pinkNoise() * 1.2 * gust;
      const noiseR = this.pinkNoiseR() * 1.2 * gust;

      let sumL = 0, sumR = 0;
      for (let r = 0; r < this.airN; r++) {
        // Advance Q walk
        this.airQWalks[r] += (this.airQTargets[r] - this.airQWalks[r]) * 0.00003;
        const q = this.airQWalks[r];
        const cutoff = Math.max(20, Math.min(sampleRate * 0.48, freq * this.airRatios[r]));
        // SVF coefficients
        const f = 2 * Math.sin(Math.PI * cutoff / sampleRate);
        const damp = Math.min(2, Math.max(0.0001, 1 / q));

        const s = this.airStates[r];
        // L
        s[0] += f * s[1];
        const highL = noiseL - s[0] - damp * s[1];
        s[1] += f * highL;
        // R
        s[2] += f * s[3];
        const highR = noiseR - s[2] - damp * s[3];
        s[3] += f * highR;

        const bandL = s[1];
        const bandR = s[3];
        const pan = this.airPans[r];
        const lGain = this.airAmps[r] * (1 - Math.max(0, pan));
        const rGain = this.airAmps[r] * (1 - Math.max(0, -pan));
        sumL += bandL * lGain;
        sumR += bandR * rGain;
      }

      // DC-block — one-pole HPF at ~20 Hz (coefficient ~0.995).
      // Strips any sub-audio drift the SVF stack can accumulate over
      // long holds without colouring the audible band.
      const dcL = sumL - this.airDcPrevL + this.airDcL * 0.995;
      this.airDcPrevL = sumL;
      this.airDcL = dcL;
      const dcR = sumR - this.airDcPrevR + this.airDcR * 0.995;
      this.airDcPrevR = sumR;
      this.airDcR = dcR;

      L[i] = dcL * amp * 0.8;
      R[i] = dcR * amp * 0.8;
    }
};



// ══ piano.js ══════════════════════════════════════════════════

// mdrone voice worklet — PIANO (stretched-harmonic + soundboard + strike) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

DroneVoiceProcessor.prototype.initPiano = function() {
    this.pianoN = 14;
    this.pianoAmps = new Float32Array([
      1.0, 0.58, 0.42, 0.28, 0.22, 0.14, 0.10, 0.06,
      0.042, 0.03, 0.022, 0.016, 0.012, 0.008,
    ]);
    // Slight inharmonic stretch — real pianos have B ≈ 0.0003..0.0015
    // for the upper partials. We approximate with a near-integer multiplier.
    this.pianoRatios = new Float32Array([
      1.0, 2.004, 3.012, 4.025, 5.04, 6.06, 7.085, 8.11,
      9.14, 10.18, 11.22, 12.27, 13.33, 14.39,
    ]);
    this.pianoPhasesL = new Float32Array(this.pianoN);
    this.pianoPhasesR = new Float32Array(this.pianoN);
    this.pianoDecay = new Float32Array(this.pianoN).fill(1);
    this.pianoDecayRates = new Float32Array(this.pianoN);
    for (let i = 0; i < this.pianoN; i++) {
      this.pianoPhasesL[i] = this.rng() * Math.PI * 2;
      this.pianoPhasesR[i] = this.rng() * Math.PI * 2;
      this.pianoDecayRates[i] = i < 2 ? 0 : 0.000008 + i * 0.000006;
    }
    this.pianoRestrikePhase = 0;
    this.pianoLfoPhase = this.rng() * Math.PI * 2;
    this.pianoLfoRate = 0.09 + this.rng() * 0.08;
    // Strike transient state — fires once at voice start to give the
    // note an attack. Decays over ~220 ms via exp envelope.
    this.pianoStrikeAge = 0;
    this.pianoStrikeDuration = Math.floor(0.22 * sampleRate);
    // Pink noise state for the strike burst (reuses class pink state).

    // Soundboard resonator — two SVF bandpasses simulating the wooden
    // body resonance of a piano soundboard. Without this the voice is
    // raw additive sines, reading as "pad with attack" rather than
    // "sustained piano matter". 220 Hz (body warmth) + 900 Hz
    // (mid presence / wood character). Mixed in parallel.
    this.pianoBodyF    = 2 * Math.sin(Math.PI * 220 / sampleRate);
    this.pianoBodyDamp = 1 / 2;      // Q = 2
    this.pianoBodyLowL  = 0;
    this.pianoBodyBandL = 0;
    this.pianoBodyLowR  = 0;
    this.pianoBodyBandR = 0;
    this.pianoMidF    = 2 * Math.sin(Math.PI * 900 / sampleRate);
    this.pianoMidDamp = 1 / 1.5;    // Q = 1.5
    this.pianoMidLowL  = 0;
    this.pianoMidBandL = 0;
    this.pianoMidLowR  = 0;
    this.pianoMidBandR = 0;
    // Presence shelf state — compensate body energy
    this.hsPianoL = 0;
    this.hsPianoR = 0;
    // Sympathetic string coupling — L/R partials bleed into each
    // other via the shared soundboard, like undamped piano strings
    // resonating sympathetically. Without this the two channels are
    // fully independent additive stacks.
    this.pianoSympathetic = 0.03;
};

DroneVoiceProcessor.prototype.pianoProcess = function(L, R, n, freq, drift, amp) {
    const invSr = 1 / sampleRate;
    const twoPi = Math.PI * 2;
    const detuneDepth = drift * 0.0028;
    const nyquist = sampleRate * 0.45;

    for (let i = 0; i < n; i++) {
      this.pianoLfoPhase += twoPi * this.pianoLfoRate * invSr;
      if (this.pianoLfoPhase > twoPi) this.pianoLfoPhase -= twoPi;
      const breath = 1 + Math.sin(this.pianoLfoPhase) * 0.025;

      this.pianoRestrikePhase += twoPi * 0.08 * invSr;
      if (this.pianoRestrikePhase > twoPi) this.pianoRestrikePhase -= twoPi;
      // Gentle re-excitation — lifts decayed partials back slightly,
      // not fully. 0.3 max avoids broadband noise from resurrected highs.
      const restrike = 0.15 + 0.15 * Math.sin(this.pianoRestrikePhase);

      let l = 0, r = 0;
      for (let p = 0; p < this.pianoN; p++) {
        this.pianoDecay[p] = Math.max(0.08, this.pianoDecay[p] - this.pianoDecayRates[p]);
        const decayEnv = this.pianoDecay[p] + (1 - this.pianoDecay[p]) * restrike * 0.5;

        const wobble = Math.sin(this.pianoLfoPhase * (1 + p * 0.13)) * detuneDepth;
        const partialFreq = freq * this.pianoRatios[p] * (1 + wobble);
        if (partialFreq > nyquist) continue;
        this.pianoPhasesL[p] += twoPi * partialFreq * invSr;
        this.pianoPhasesR[p] += twoPi * partialFreq * invSr * (1 + detuneDepth * 0.45) * this.dichoticMulR;
        if (this.pianoPhasesL[p] > twoPi) this.pianoPhasesL[p] -= twoPi;
        if (this.pianoPhasesR[p] > twoPi) this.pianoPhasesR[p] -= twoPi;

        const a = this.pianoAmps[p] * breath * decayEnv;
        l += fastSin(this.pianoPhasesL[p]) * a;
        r += fastSin(this.pianoPhasesR[p]) * a;
      }
      l *= 0.16;
      r *= 0.16;
      // Sympathetic string coupling — cross-bleed via soundboard
      const pSym = this.pianoSympathetic;
      const plB = l + r * pSym;
      const prB = r + l * pSym;
      l = plB;
      r = prB;

      // Strike transient — a decaying pink-noise burst during the first
      // ~220 ms of the voice. Gives it a hammer-hit attack.
      if (this.pianoStrikeAge < this.pianoStrikeDuration) {
        const t = this.pianoStrikeAge / this.pianoStrikeDuration;
        const strikeEnv = Math.exp(-t * 7);
        const strike = this.pinkNoise() * strikeEnv * 0.2;
        l += strike;
        r += strike * 0.96; // tiny stereo spread
        this.pianoStrikeAge++;
      }

      // Soundboard resonator — parallel bandpass peaks at 220 Hz
      // (body) and 900 Hz (mid/wood). Same SVF technique as tanpura
      // body: band outputs mixed into the dry signal.
      const pbHL = l - this.pianoBodyLowL - this.pianoBodyDamp * this.pianoBodyBandL;
      this.pianoBodyBandL += this.pianoBodyF * pbHL;
      this.pianoBodyLowL  += this.pianoBodyF * this.pianoBodyBandL;
      const pmHL = l - this.pianoMidLowL - this.pianoMidDamp * this.pianoMidBandL;
      this.pianoMidBandL += this.pianoMidF * pmHL;
      this.pianoMidLowL  += this.pianoMidF * this.pianoMidBandL;
      const pbHR = r - this.pianoBodyLowR - this.pianoBodyDamp * this.pianoBodyBandR;
      this.pianoBodyBandR += this.pianoBodyF * pbHR;
      this.pianoBodyLowR  += this.pianoBodyF * this.pianoBodyBandR;
      const pmHR = r - this.pianoMidLowR - this.pianoMidDamp * this.pianoMidBandR;
      this.pianoMidBandR += this.pianoMidF * pmHR;
      this.pianoMidLowR  += this.pianoMidF * this.pianoMidBandR;
      l += this.pianoBodyBandL * 0.15 + this.pianoMidBandL * 0.10;
      r += this.pianoBodyBandR * 0.15 + this.pianoMidBandR * 0.10;

      // Gentle high-frequency rolloff — the 14 partials produce enough
      // brightness naturally. The one-pole LP tames content above ~4 kHz
      // that reveals as "frrr" on bright headphones (DT990 etc).
      this.hsPianoL = this.hsPianoL * 0.12 + l * 0.88;
      this.hsPianoR = this.hsPianoR * 0.12 + r * 0.88;
      l = this.hsPianoL;
      r = this.hsPianoR;

      L[i] = l * amp;
      R[i] = r * amp;
    }
};

  // dominant tonal with a characteristic inharmonic shimmer. Used for



// ══ fm.js ══════════════════════════════════════════════════

// mdrone voice worklet — FM (2-op with slow index envelope) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

DroneVoiceProcessor.prototype.initFm = function() {
    this.fmCarrierPhaseL = this.rng() * Math.PI * 2;
    this.fmCarrierPhaseR = this.rng() * Math.PI * 2;
    this.fmModPhase = this.rng() * Math.PI * 2;
    this.fmRatio = this.fmRatioOpt;  // modulator : carrier frequency ratio (from preset)
    this.fmIndex = this.fmIndexOpt; // modulation index (from preset)
    // Modulator self-feedback (0..1). Feeds the previous modulator
    // output back into its own phase, producing richer/grittier
    // timbres (metallic drones, harsh bells). 0 = classic 2-op,
    // 0.3 = warm thickening, 0.7+ = aggressive/noisy. Default 0
    // preserves existing presets.
    this.fmFeedback = this.fmFeedbackOpt;
    this.fmModFbSample = 0; // one-sample feedback delay
    this.fmLfoPhase = this.rng() * Math.PI * 2;
    this.fmLfoRate = 0.08 + this.rng() * 0.06;
    // Slow index-envelope LFO — modulates fmIndex across ~±55 % so
    // the bell "rings out" and comes back over a 30-50 s period.
    // Fixed 2.0 index is audibly static; this is what turns a dead
    // DX7-style bell into a living one.
    this.fmIndexLfoPhase = this.rng() * Math.PI * 2;
    this.fmIndexLfoRate = 0.015 + this.rng() * 0.012;
};

DroneVoiceProcessor.prototype.fmProcess = function(L, R, n, freq, drift, amp) {
    const invSr = 1 / sampleRate;
    const twoPi = Math.PI * 2;
    const depth = drift * 0.004;
    // Anti-alias headroom — Carson's rule says FM bandwidth ≈
    // 2·modFreq·(1 + index), so the highest reproduced sideband is
    // at ≈ carrier + modFreq·(1 + index). For aliasing to stay
    // inaudible we keep that under Nyquist · 0.85. Solving for
    // index gives a per-sample upper bound; we soft-cap dynIndex
    // through tanh so the bell still rings at high frequencies but
    // can never push energy past the alias headroom. Cheap (one
    // tanh per sample) and avoids the per-voice halfband we would
    // otherwise need for an oscillator-style 2× oversample.
    const aliasHeadroom = sampleRate * 0.5 * 0.85;

    for (let i = 0; i < n; i++) {
      this.fmLfoPhase += twoPi * this.fmLfoRate * invSr;
      if (this.fmLfoPhase > twoPi) this.fmLfoPhase -= twoPi;
      const breath = 1 + Math.sin(this.fmLfoPhase) * 0.035;

      // Slow index envelope — sidebands bloom and recede over tens
      // of seconds so the voice is never harmonically static.
      this.fmIndexLfoPhase += twoPi * this.fmIndexLfoRate * invSr;
      if (this.fmIndexLfoPhase > twoPi) this.fmIndexLfoPhase -= twoPi;
      const rawIndex = this.fmIndex * (1 + Math.sin(this.fmIndexLfoPhase) * 0.55);
      // Modulator frequency for this sample — used both for the
      // oscillator and for the alias headroom calculation.
      const modFreq = freq * this.fmRatio * (1 + depth);
      const maxIndex = Math.max(0.1, (aliasHeadroom - freq) / Math.max(modFreq, 1) - 1);
      const dynIndex = maxIndex * Math.tanh(rawIndex / maxIndex);
      const fbPhase = this.fmModPhase + this.fmFeedback * this.fmModFbSample;
      this.fmModPhase += twoPi * modFreq * invSr;
      if (this.fmModPhase > twoPi) this.fmModPhase -= twoPi;
      const modSin = fastSin(fbPhase);
      this.fmModFbSample = modSin; // store for next sample's feedback
      const modOut = modSin * dynIndex * freq;

      // Carrier oscillators — frequency-modulated by the modulator
      const cFreq = freq + modOut;
      this.fmCarrierPhaseL += twoPi * cFreq * invSr;
      this.fmCarrierPhaseR += twoPi * cFreq * invSr * (1 + depth * 0.6) * this.dichoticMulR;
      while (this.fmCarrierPhaseL >  twoPi) this.fmCarrierPhaseL -= twoPi;
      while (this.fmCarrierPhaseL < -twoPi) this.fmCarrierPhaseL += twoPi;
      while (this.fmCarrierPhaseR >  twoPi) this.fmCarrierPhaseR -= twoPi;
      while (this.fmCarrierPhaseR < -twoPi) this.fmCarrierPhaseR += twoPi;

      const s = breath * 0.22;
      L[i] = fastSin(this.fmCarrierPhaseL) * s * amp;
      R[i] = fastSin(this.fmCarrierPhaseR) * s * amp;
    }
};

  // hard through tanh saturation with a simulated cabinet low-pass.



// ══ amp.js ══════════════════════════════════════════════════

// mdrone voice worklet — AMP (tube-bias cabinet with speaker feedback) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated
// after core.js by scripts/build-worklet.mjs.

// Per-voice loudness trim. Applied at output write so all AMP-using
// presets shift uniformly. AMP voice intrinsic gain was tuned for peak
// headroom, not equal-loudness parity — `sunn-amp-drone` measured at
// -23.1 LUFS (1.20.14 audit), the 4th-loudest preset, ~5-9 dB above
// the polite -28 to -32 LUFS middle. -4 dB (x0.63) lands sunn-amp-drone
// at the edge of polite range without overshooting AMP's harmonic
// identity (less concentrated in 2-8 kHz than tanpura's jawari, so a
// smaller trim than TANPURA_INTRINSIC_GAIN = 0.5).
const AMP_INTRINSIC_GAIN = 0.63;

DroneVoiceProcessor.prototype.initAmp = function() {
    this.ampN = 6;
    this.ampAmps      = new Float32Array([1.0, 0.55, 0.38, 0.22, 0.14, 0.08]);
    this.ampPhasesL   = new Float32Array(this.ampN);
    this.ampPhasesR   = new Float32Array(this.ampN);
    for (let i = 0; i < this.ampN; i++) {
      this.ampPhasesL[i] = this.rng() * Math.PI * 2;
      this.ampPhasesR[i] = this.rng() * Math.PI * 2;
    }
    this.ampLfoPhase = this.rng() * Math.PI * 2;
    this.ampLfoRate = 0.06 + this.rng() * 0.08;
    // Cabinet shaper — a proper guitar-cab-style response needs a
    // tighter body resonance (~95 Hz Q≈3), a focused presence peak
    // (~2.8 kHz Q≈5) — the previous broad Q≈1.8 peak smeared into
    // 4-6 kHz fizz — and a steeper rolloff above ~6.5 kHz. The cab
    // LP is now a *cascaded* one-pole pair (≈ 12 dB/oct at the
    // corner) to kill the harshness from the asymmetric tanh's
    // upper harmonics without needing a true biquad.
    this.ampBodyF    = 2 * Math.sin(Math.PI * 95   / sampleRate);
    this.ampBodyDamp = 1 / 3;      // Q = 3
    this.ampBodyLowL  = 0;
    this.ampBodyBandL = 0;
    this.ampBodyLowR  = 0;
    this.ampBodyBandR = 0;
    this.ampPresF    = 2 * Math.sin(Math.PI * 2800 / sampleRate);
    this.ampPresDamp = 1 / 5;      // Q = 5
    this.ampPresLowL  = 0;
    this.ampPresBandL = 0;
    this.ampPresLowR  = 0;
    this.ampPresBandR = 0;
    // Two-stage cabinet lowpass state — cascaded one-poles at 6.5 kHz
    // give ≈ 12 dB/oct rolloff (–3 dB at 6.5 kHz, –12 dB at 13 kHz).
    this.ampCabL  = 0;
    this.ampCabR  = 0;
    this.ampCab2L = 0;
    this.ampCab2R = 0;
    // DC blocker state — removes offset from asymmetric saturation.
    this.ampDcPrevInL  = 0;
    this.ampDcPrevOutL = 0;
    this.ampDcPrevInR  = 0;
    this.ampDcPrevOutR = 0;
    // Speaker feedback — a tiny fraction of cabinet output feeds back
    // into the saturation input, simulating how real speakers excite
    // the preamp via physical coupling. Makes the amp self-exciting
    // at a controlled level instead of a static chain. Reduced from
    // 0.06 to 0.045 because the steeper 2-stage cab now has a slower
    // settling time and the higher-Q body BPF amplifies any residual
    // sub-fundamental energy in the feedback path.
    this.ampSpkFbL = 0;
    this.ampSpkFbR = 0;
    // 2× halfband oversamplers around the asymmetric tanh — the
    // biggest aliasing hotspot in the engine (k=3.8, 6 harmonics in).
    this.ampHbL = new Halfband2x();
    this.ampHbR = new Halfband2x();
};

DroneVoiceProcessor.prototype.ampProcess = function(L, R, n, freq, drift, amp) {
    const invSr = 1 / sampleRate;
    const twoPi = Math.PI * 2;
    const detuneDepth = drift * 0.005;
    // Final cabinet rolloff — cascaded one-pole pair at 6.5 kHz gives
    // a 2-pole (≈ 12 dB/oct) response. The presence peak at 2.8 kHz
    // sits a bit over an octave below the corner so it passes through
    // largely intact, while the asymmetric-tanh's 4-8 kHz "fizz"
    // harmonics get steeper attenuation than a single-pole could give.
    const cabCoef = Math.exp(-twoPi * 6500 * invSr);
    const cabOneMinus = 1 - cabCoef;
    // Hoisted shaper — allocating the arrow inside the sample loop
    // created a closure per sample, which Safari's JSC doesn't escape-
    // analyse away. The GC pressure inside the realtime audio callback
    // produced the signal-correlated "frrrr" hash on Safari.
    const bias = 0.12;
    const ampShaper = (v) => Math.tanh((v + bias) * 3.8) * 0.72;

    for (let i = 0; i < n; i++) {
      this.ampLfoPhase += twoPi * this.ampLfoRate * invSr;
      if (this.ampLfoPhase > twoPi) this.ampLfoPhase -= twoPi;
      const swell = 1 + Math.sin(this.ampLfoPhase) * 0.12;

      let l = 0, r = 0;
      for (let p = 0; p < this.ampN; p++) {
        const wobble = Math.sin(this.ampLfoPhase * (1 + p * 0.17)) * detuneDepth;
        const partialFreq = freq * (p + 1) * (1 + wobble);
        this.ampPhasesL[p] += twoPi * partialFreq * invSr;
        this.ampPhasesR[p] += twoPi * partialFreq * invSr * (1 + detuneDepth * 0.7) * this.dichoticMulR;
        if (this.ampPhasesL[p] > twoPi) this.ampPhasesL[p] -= twoPi;
        if (this.ampPhasesR[p] > twoPi) this.ampPhasesR[p] -= twoPi;

        l += fastSin(this.ampPhasesL[p]) * this.ampAmps[p];
        r += fastSin(this.ampPhasesR[p]) * this.ampAmps[p];
      }
      l *= swell;
      r *= swell;
      // Speaker feedback — cabinet resonance feeds back into preamp
      l += this.ampSpkFbL * 0.045;
      r += this.ampSpkFbR * 0.045;
      // Asymmetric soft-clip — a small positive DC bias before tanh
      // causes positive peaks to clip earlier than negative, generating
      // even harmonics (2nd, 4th…) like a real tube amplifier. Without
      // this the voice has only odd-harmonic distortion character.
      // Wrapped in a 2× halfband oversampler so the harmonic content
      // generated above Nyquist doesn't fold back into the audible band.
      l = this.ampHbL.process(l, ampShaper);
      r = this.ampHbR.process(r, ampShaper);
      // DC blocker — removes the offset introduced by asymmetric clip
      const dcCoef = 0.995;
      const dcOutL = l - this.ampDcPrevInL + dcCoef * this.ampDcPrevOutL;
      this.ampDcPrevInL = l; this.ampDcPrevOutL = dcOutL;
      l = dcOutL;
      const dcOutR = r - this.ampDcPrevInR + dcCoef * this.ampDcPrevOutR;
      this.ampDcPrevInR = r; this.ampDcPrevOutR = dcOutR;
      r = dcOutR;

      // Cabinet shaper: tighter body BPF (95 Hz Q≈3), focused
      // presence BPF (2.8 kHz Q≈5), then a 2-stage cab LP at 6.5 kHz.
      // Bandpass mix gains lowered (0.30/0.25 vs. 0.35/0.28) to keep
      // RMS roughly equal-loudness with the previous broader voicing.
      // +1e-25 on the band-state writes is a denormal escape under
      // long silences (the higher-Q SVFs ring far below audible).
      const bHL = l - this.ampBodyLowL - this.ampBodyDamp * this.ampBodyBandL;
      this.ampBodyBandL += this.ampBodyF * bHL + 1e-20;
      this.ampBodyLowL  += this.ampBodyF * this.ampBodyBandL;
      const pHL = l - this.ampPresLowL - this.ampPresDamp * this.ampPresBandL;
      this.ampPresBandL += this.ampPresF * pHL + 1e-20;
      this.ampPresLowL  += this.ampPresF * this.ampPresBandL;
      const shapedL = l + this.ampBodyBandL * 0.30 + this.ampPresBandL * 0.25;

      const bHR = r - this.ampBodyLowR - this.ampBodyDamp * this.ampBodyBandR;
      this.ampBodyBandR += this.ampBodyF * bHR + 1e-20;
      this.ampBodyLowR  += this.ampBodyF * this.ampBodyBandR;
      const pHR = r - this.ampPresLowR - this.ampPresDamp * this.ampPresBandR;
      this.ampPresBandR += this.ampPresF * pHR + 1e-20;
      this.ampPresLowR  += this.ampPresF * this.ampPresBandR;
      const shapedR = r + this.ampBodyBandR * 0.30 + this.ampPresBandR * 0.25;

      // 2-stage cabinet LP — first pole, then second pole on the result.
      this.ampCabL  = this.ampCabL  * cabCoef + shapedL       * cabOneMinus;
      this.ampCab2L = this.ampCab2L * cabCoef + this.ampCabL  * cabOneMinus;
      this.ampCabR  = this.ampCabR  * cabCoef + shapedR       * cabOneMinus;
      this.ampCab2R = this.ampCab2R * cabCoef + this.ampCabR  * cabOneMinus;
      // Speaker feedback taken from the second-stage output so the
      // self-exciting loop sees the full cab response, not the mid
      // of the two-stage cascade.
      this.ampSpkFbL = this.ampCab2L;
      this.ampSpkFbR = this.ampCab2R;
      L[i] = this.ampCab2L * amp * AMP_INTRINSIC_GAIN;
      R[i] = this.ampCab2R * amp * AMP_INTRINSIC_GAIN;
    }
};



// ══ noise.js ══════════════════════════════════════════════════

// mdrone voice worklet — NOISE (untuned broadband bed) voice.
// Prototype extensions on DroneVoiceProcessor; concatenated after
// core.js by scripts/build-worklet.mjs.
//
// Design intent: deliver the one thing the seven existing voices
// cannot — untuned, tonic-independent broadband noise for hiss
// beds, wind washes, ritual dust, tape-hiss nostalgia, rain / wind
// ambiance, industrial rumble. Drone canon uses noise as a primary
// layer (Basinski, Radigue, La Monte Young, Hecker, Deathprod);
// mdrone previously required leaving the app to add any of it.
//
// Single user-facing knob: COLOR (0..1), routed into the worklet
// via the `color` AudioParam.
//
//   0.00  white       — bright, full-spectrum hiss
//   0.30  pink        — natural, "rain on leaves"
//   0.60  brown       — rumble, "distant surf"
//   0.85  deep brown  — subsonic ritual floor
//   1.00  sub-rumble  — body-weight bed
//
// The slider maps to a one-pole lowpass cutoff mapped exponentially
// from 20 kHz to 40 Hz and to a white→pink mix. Plus a hard-coded
// slow amplitude LFO (~0.03 Hz, ±10%) so the bed "breathes" rather
// than sitting dead flat — matches mdrone's per-voice physicality
// philosophy (tanpura auto-repluck, amp swell, metal re-excitation).
//
// Tonic-independent: `freq` is ignored. `drift` is unused. The voice
// doesn't respond to tonic changes — that's the whole point.

DroneVoiceProcessor.prototype.initNoise = function() {
  // Independent pink-noise state for the R channel so the stereo
  // image isn't mono — white sources share this.rng but pass through
  // decorrelated filter states, which already gives some width.
  this.noisePinkR = { b0: 0, b1: 0, b2: 0, b3: 0, b4: 0, b5: 0, b6: 0 };
  // One-pole lowpass state per channel (the "color" shaper).
  this.noiseLpL = 0;
  this.noiseLpR = 0;
  // Slow amplitude LFO — ~0.03 Hz, ±10%. Not user-adjustable.
  this.noiseLfoPhase = this.rng() * Math.PI * 2;
  this.noiseLfoRateHz = 0.03;
  // DC-block HPF state per channel — a lowpass fed by noise can
  // accumulate tiny DC offset over long holds.
  this.noiseDcL = 0;
  this.noiseDcR = 0;
  this.noiseDcPrevL = 0;
  this.noiseDcPrevR = 0;
};

// Secondary pink generator for R using noisePinkR state. Mirrors
// AIR's pinkNoiseR pattern so stereo isn't a mono source.
DroneVoiceProcessor.prototype.noisePinkNoiseR = function() {
  const p = this.noisePinkR;
  const white = this.rng() * 2 - 1;
  p.b0 = 0.99886 * p.b0 + white * 0.0555179;
  p.b1 = 0.99332 * p.b1 + white * 0.0750759;
  p.b2 = 0.969  * p.b2 + white * 0.153852;
  p.b3 = 0.8665 * p.b3 + white * 0.3104856;
  p.b4 = 0.55   * p.b4 + white * 0.5329522;
  p.b5 = -0.7616 * p.b5 - white * 0.016898;
  const out = p.b0 + p.b1 + p.b2 + p.b3 + p.b4 + p.b5 + p.b6 + white * 0.5362;
  p.b6 = white * 0.115926;
  return out * 0.11;
};

DroneVoiceProcessor.prototype.noiseProcess = function(L, R, n, _freq, _drift, amp, color) {
  // COLOR → lowpass cutoff (exponential 20 kHz → 40 Hz). The map is
  // exponential because human pitch/cutoff perception is log — a
  // linear slider feels right only with an exponential mapping.
  const c = Math.max(0, Math.min(1, color));
  const cutoffHz = 20000 * Math.pow(40 / 20000, c);
  const cutoffClamped = Math.max(20, Math.min(sampleRate * 0.49, cutoffHz));
  // One-pole lowpass coefficient (standard RC-style):
  //   y[n] = lpCoef * y[n-1] + (1 - lpCoef) * x[n]
  const lpCoef = Math.exp(-2 * Math.PI * cutoffClamped / sampleRate);
  const oneMinusLp = 1 - lpCoef;

  // White↔pink crossfade. Pure white at color = 0 (pre-filter, so
  // filter has nothing to do and output is full white); pink from
  // c ≈ 0.2 onwards; filter does the brown/deep shaping past that.
  const pinkMix = Math.min(1, c * 2.5);
  const whiteMix = 1 - pinkMix;
  // Pink amplitude is ~3 dB lower than white for equal subjective
  // loudness; multiply by 1.5 to compensate in the mix.
  const pinkScale = 1.5;

  // Gain compensation — a lowpass at 40 Hz kills most of the
  // audible spectrum; boost to keep subjective loudness roughly
  // constant across the COLOR range. Empirical: ~+12 dB at c=1.
  const gainComp = 1 + c * 4;

  // Final output scaling — tuned so that level 1 sits slightly
  // quieter than other voices at their reference levels (noise is
  // easy to turn into an overpowering bed; err on the quiet side).
  const outScale = 0.5;

  const twoPi = Math.PI * 2;
  const invSr = 1 / sampleRate;

  for (let i = 0; i < n; i++) {
    // Slow amplitude LFO — hard-coded physicality.
    this.noiseLfoPhase += twoPi * this.noiseLfoRateHz * invSr;
    if (this.noiseLfoPhase > twoPi) this.noiseLfoPhase -= twoPi;
    const lfo = 1 + Math.sin(this.noiseLfoPhase) * 0.10;

    // White sources (independent L/R via independent rng() calls).
    const whiteL = this.rng() * 2 - 1;
    const whiteR = this.rng() * 2 - 1;
    // Pink sources — share the core pink state for L, independent for R.
    const pinkL = this.pinkNoise();
    const pinkR = this.noisePinkNoiseR();

    const srcL = whiteL * whiteMix + pinkL * pinkMix * pinkScale;
    const srcR = whiteR * whiteMix + pinkR * pinkMix * pinkScale;

    // One-pole lowpass — brown / deep end.
    this.noiseLpL = lpCoef * this.noiseLpL + oneMinusLp * srcL;
    this.noiseLpR = lpCoef * this.noiseLpR + oneMinusLp * srcR;

    // Gain comp + LFO.
    const preL = this.noiseLpL * gainComp * lfo;
    const preR = this.noiseLpR * gainComp * lfo;

    // DC-block (HPF ~8 Hz, coefficient 0.998).
    const dcL = preL - this.noiseDcPrevL + this.noiseDcL * 0.998;
    this.noiseDcPrevL = preL;
    this.noiseDcL = dcL;
    const dcR = preR - this.noiseDcPrevR + this.noiseDcR * 0.998;
    this.noiseDcPrevR = preR;
    this.noiseDcR = dcR;

    L[i] = dcL * amp * outScale;
    R[i] = dcR * amp * outScale;
  }
};



// ══ register.js ══════════════════════════════════════════════════

// mdrone voice worklet — processor registration. Must come last in
// the concatenation order so every per-voice prototype extension is
// already attached to DroneVoiceProcessor before it is handed to
// AudioWorkletGlobalScope.

registerProcessor("drone-voice", DroneVoiceProcessor);

