#!/usr/bin/env node
// Concatenates the voice worklet's split source modules under
// `src/engine/voices/` into the single entry file the runtime ships
// (`src/engine/droneVoiceProcessor.js`). AudioWorklet cannot portably
// import ES modules yet, so we ship one physical file but author the
// source as separate modules.
//
// Current split:
//   - src/engine/voices/shared.js  → helpers (rng, fastSin, polyblep,
//                                     Halfband2x)
//   - src/engine/voices/core.js    → the DroneVoiceProcessor class
//                                     with its registerProcessor call
//
// Add more per-voice files here as the staged split continues (see
// misc/2026-04-16-AUDIT.md — voice-processor split P1 item).

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const VOICES = join(ROOT, "src/engine/voices");
const OUT = join(ROOT, "src/engine/droneVoiceProcessor.js");

const HEADER = `/**
 * droneVoiceProcessor — generated by scripts/build-worklet.mjs.
 * DO NOT EDIT THIS FILE DIRECTLY — edit the source under
 * src/engine/voices/ and re-run \`npm run prebuild\`.
 *
 * This worklet is loaded by Vite via \`?url\` import and registered
 * into AudioWorkletGlobalScope. AudioWorklet cannot portably import
 * ES modules, so the source is split for maintainability and
 * concatenated here to ship as a single file.
 */

/* sampleRate, AudioWorkletProcessor, registerProcessor are globals in AudioWorkletGlobalScope */
/* global sampleRate, AudioWorkletProcessor, registerProcessor */
`;

function readSource(path) {
  return readFileSync(path, "utf8");
}

// Concatenation order matters — shared.js must come first because
// core.js references Halfband2x / fastSin / polyblep / makeRng.
const ORDER = ["shared.js", "core.js"];

function build() {
  const parts = [HEADER];
  for (const name of ORDER) {
    const fullPath = join(VOICES, name);
    if (!existsSync(fullPath)) {
      console.warn(`[build-worklet] skipping missing ${fullPath} — staged split in progress`);
      return null;
    }
    const src = readSource(fullPath);
    // Strip duplicate /* global ... */ directives from split files;
    // the generated header carries them.
    const stripped = src.replace(/^\s*\/\* global [^*]+\*\//gm, "");
    parts.push(`\n// ══ ${name} ══════════════════════════════════════════════════\n`);
    parts.push(stripped.trim());
    parts.push("\n");
  }
  return parts.join("\n");
}

const content = build();
if (content) {
  writeFileSync(OUT, content);
  console.log(`[build-worklet] wrote ${OUT} from ${ORDER.length} modules`);
} else {
  console.log(`[build-worklet] staged split incomplete — leaving ${OUT} as-is`);
}
